import type { ExerciseMetadata } from './types'

export const EXERCISE_DATABASE: ExerciseMetadata[] = [
  {
    id: 'barbell_bench_press',
    name: 'Barbell Bench Press',
    movement_category: 'horizontal_press',
    movementCategory: 'horizontal_press',
    primary_muscles: ['chest'],
    secondary_muscles: ['front_delts', 'triceps'],
    fatigue_rating: 'high',
    fatigueClass: 'high_pressing',
    systemic_fatigue: 'high',
    stability_requirement: 'moderate',
    equipment_type: ['barbell', 'bench'],
    stimulus_profile: ['strength', 'hypertrophy'],
    difficulty_level: 'intermediate',
    compoundType: 'compound_press',
    overlapTags: ['chest_pressing', 'front_delt', 'triceps_pressing'],
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    movement_category: 'incline_press',
    movementCategory: 'incline_press',
    primary_muscles: ['upper_chest'],
    secondary_muscles: ['front_delts', 'triceps'],
    fatigue_rating: 'moderate',
    fatigueClass: 'high_pressing',
    systemic_fatigue: 'moderate',
    stability_requirement: 'moderate',
    equipment_type: ['dumbbells', 'bench'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'intermediate',
    compoundType: 'compound_press',
    overlapTags: ['chest_pressing', 'front_delt', 'triceps_pressing'],
  },
  {
    id: 'machine_chest_press',
    name: 'Machine Chest Press',
    movement_category: 'horizontal_press',
    movementCategory: 'horizontal_press',
    primary_muscles: ['chest'],
    secondary_muscles: ['front_delts', 'triceps'],
    fatigue_rating: 'moderate',
    fatigueClass: 'high_pressing',
    systemic_fatigue: 'moderate',
    stability_requirement: 'low',
    equipment_type: ['machine'],
    stimulus_profile: ['hypertrophy', 'strength'],
    difficulty_level: 'beginner',
    compoundType: 'compound_press',
    overlapTags: ['chest_pressing', 'front_delt', 'triceps_pressing'],
  },
  {
    id: 'cable_fly',
    name: 'Cable Fly',
    movement_category: 'chest_isolation',
    movementCategory: 'chest_isolation',
    primary_muscles: ['chest'],
    secondary_muscles: ['front_delts'],
    fatigue_rating: 'low',
    fatigueClass: 'low_fatigue',
    systemic_fatigue: 'low',
    stability_requirement: 'low',
    equipment_type: ['cable_machine'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
    compoundType: 'isolation',
    overlapTags: ['chest_pressing', 'low_fatigue_accessory'],
  },
  {
    id: 'seated_dumbbell_shoulder_press',
    name: 'Seated Dumbbell Shoulder Press',
    movement_category: 'vertical_press',
    movementCategory: 'vertical_press',
    primary_muscles: ['front_delts', 'lateral_delts'],
    secondary_muscles: ['triceps', 'upper_chest'],
    fatigue_rating: 'moderate',
    fatigueClass: 'high_pressing',
    systemic_fatigue: 'moderate',
    stability_requirement: 'moderate',
    equipment_type: ['dumbbells', 'bench'],
    stimulus_profile: ['strength', 'hypertrophy'],
    difficulty_level: 'intermediate',
    compoundType: 'compound_press',
    overlapTags: ['shoulder_pressing', 'front_delt', 'triceps_pressing'],
  },
  {
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    movement_category: 'shoulder_isolation',
    movementCategory: 'shoulder_isolation',
    primary_muscles: ['lateral_delts'],
    secondary_muscles: ['traps'],
    fatigue_rating: 'low',
    fatigueClass: 'low_fatigue',
    systemic_fatigue: 'low',
    stability_requirement: 'low',
    equipment_type: ['cable_machine'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
    compoundType: 'isolation',
    overlapTags: ['low_fatigue_accessory'],
  },
  {
    id: 'chest_supported_row',
    name: 'Chest-Supported Row',
    movement_category: 'horizontal_pull',
    primary_muscles: ['upper_back', 'lats'],
    secondary_muscles: ['rear_delts', 'biceps'],
    fatigue_rating: 'moderate',
    systemic_fatigue: 'moderate',
    stability_requirement: 'low',
    equipment_type: ['machine', 'dumbbells'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    movement_category: 'horizontal_pull',
    primary_muscles: ['upper_back', 'lats'],
    secondary_muscles: ['rear_delts', 'biceps'],
    fatigue_rating: 'moderate',
    systemic_fatigue: 'moderate',
    stability_requirement: 'low',
    equipment_type: ['cable_machine'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    movement_category: 'horizontal_pull',
    primary_muscles: ['upper_back', 'lats'],
    secondary_muscles: ['rear_delts', 'biceps', 'lower_back'],
    fatigue_rating: 'high',
    systemic_fatigue: 'high',
    stability_requirement: 'high',
    equipment_type: ['barbell'],
    stimulus_profile: ['strength', 'hypertrophy'],
    difficulty_level: 'advanced',
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    movement_category: 'vertical_pull',
    primary_muscles: ['lats'],
    secondary_muscles: ['biceps', 'upper_back'],
    fatigue_rating: 'moderate',
    systemic_fatigue: 'low',
    stability_requirement: 'low',
    equipment_type: ['cable_machine'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'assisted_pull_up',
    name: 'Assisted Pull-Up',
    movement_category: 'vertical_pull',
    primary_muscles: ['lats'],
    secondary_muscles: ['biceps', 'upper_back', 'abs'],
    fatigue_rating: 'moderate',
    systemic_fatigue: 'moderate',
    stability_requirement: 'moderate',
    equipment_type: ['machine', 'pull_up_bar'],
    stimulus_profile: ['strength', 'hypertrophy'],
    difficulty_level: 'intermediate',
  },
  {
    id: 'back_squat',
    name: 'Back Squat',
    movement_category: 'squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['adductors', 'deep_core', 'lower_back'],
    fatigue_rating: 'high',
    systemic_fatigue: 'high',
    stability_requirement: 'high',
    equipment_type: ['barbell'],
    stimulus_profile: ['strength', 'hypertrophy'],
    difficulty_level: 'advanced',
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    movement_category: 'squat',
    primary_muscles: ['quads'],
    secondary_muscles: ['glutes', 'adductors'],
    fatigue_rating: 'moderate',
    systemic_fatigue: 'moderate',
    stability_requirement: 'low',
    equipment_type: ['machine'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    movement_category: 'squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['adductors'],
    fatigue_rating: 'moderate',
    systemic_fatigue: 'moderate',
    stability_requirement: 'low',
    equipment_type: ['machine'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    movement_category: 'hinge',
    primary_muscles: ['hamstrings', 'glutes'],
    secondary_muscles: ['lower_back', 'upper_back'],
    fatigue_rating: 'high',
    systemic_fatigue: 'high',
    stability_requirement: 'moderate',
    equipment_type: ['barbell', 'dumbbells'],
    stimulus_profile: ['strength', 'hypertrophy'],
    difficulty_level: 'intermediate',
  },
  {
    id: 'seated_leg_curl',
    name: 'Seated Leg Curl',
    movement_category: 'hinge',
    primary_muscles: ['hamstrings'],
    secondary_muscles: [],
    fatigue_rating: 'low',
    systemic_fatigue: 'low',
    stability_requirement: 'low',
    equipment_type: ['machine'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    movement_category: 'unilateral_lower',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['hamstrings', 'deep_core'],
    fatigue_rating: 'moderate',
    systemic_fatigue: 'moderate',
    stability_requirement: 'high',
    equipment_type: ['dumbbells', 'bench'],
    stimulus_profile: ['hypertrophy', 'stability'],
    difficulty_level: 'intermediate',
  },
  {
    id: 'walking_lunge',
    name: 'Walking Lunge',
    movement_category: 'unilateral_lower',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['hamstrings', 'calves', 'deep_core'],
    fatigue_rating: 'moderate',
    systemic_fatigue: 'moderate',
    stability_requirement: 'high',
    equipment_type: ['dumbbells', 'bodyweight'],
    stimulus_profile: ['hypertrophy', 'conditioning', 'stability'],
    difficulty_level: 'intermediate',
  },
  {
    id: 'bayesian_curl',
    name: 'Bayesian Curl',
    movement_category: 'biceps_isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: ['forearms'],
    fatigue_rating: 'low',
    systemic_fatigue: 'low',
    stability_requirement: 'low',
    equipment_type: ['cable_machine'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    movement_category: 'biceps_isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: ['forearms'],
    fatigue_rating: 'low',
    systemic_fatigue: 'low',
    stability_requirement: 'moderate',
    equipment_type: ['dumbbells', 'bench'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'cable_pushdown',
    name: 'Cable Pushdown',
    movement_category: 'triceps_isolation',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    fatigue_rating: 'low',
    systemic_fatigue: 'low',
    stability_requirement: 'low',
    equipment_type: ['cable_machine'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'overhead_cable_triceps_extension',
    name: 'Overhead Cable Triceps Extension',
    movement_category: 'triceps_isolation',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    fatigue_rating: 'low',
    systemic_fatigue: 'low',
    stability_requirement: 'low',
    equipment_type: ['cable_machine'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'standing_calf_raise',
    name: 'Standing Calf Raise',
    movement_category: 'calves',
    primary_muscles: ['calves'],
    secondary_muscles: [],
    fatigue_rating: 'low',
    systemic_fatigue: 'low',
    stability_requirement: 'low',
    equipment_type: ['machine', 'dumbbells'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'cable_crunch',
    name: 'Cable Crunch',
    movement_category: 'abs_core',
    primary_muscles: ['abs'],
    secondary_muscles: ['deep_core'],
    fatigue_rating: 'low',
    systemic_fatigue: 'low',
    stability_requirement: 'low',
    equipment_type: ['cable_machine'],
    stimulus_profile: ['hypertrophy'],
    difficulty_level: 'beginner',
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    movement_category: 'abs_core',
    primary_muscles: ['deep_core'],
    secondary_muscles: ['abs'],
    fatigue_rating: 'low',
    systemic_fatigue: 'low',
    stability_requirement: 'low',
    equipment_type: ['bodyweight'],
    stimulus_profile: ['stability'],
    difficulty_level: 'beginner',
  },
]
